trigger:
- main  # Trigger the pipeline when changes are pushed to the main branch

pool:
  vmImage: 'ubuntu-latest'  # Use the latest Ubuntu image

steps:
- task: UseJavaVersion@1
  inputs:
    versionSpec: '11'  # Specify Java version (e.g., OpenJDK 11)
  displayName: 'Set up JDK'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'  # Path to your pom.xml file
    goals: 'clean install'  # Clean and install the application
    options: '-DskipTests'  # Skip tests during the build (optional, can be removed if you want to run tests during the build)
  displayName: 'Build with Maven'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'  # Path to your pom.xml file
    goals: 'test'  # Run the tests
  displayName: 'Run Unit Tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'  # Format for test results
    testResultsFiles: '**/target/test-*.xml'  # Path to the test results
    mergeTestResults: true  # Merge test results if there are multiple files
  displayName: 'Publish Test Results'
