trigger:
- main  # Trigger the pipeline when changes are pushed to the main branch

pool:
  name: default  # Use the latest Ubuntu image

steps:
# Manually set up Java environment using a script
- script: |
    sudo apt-get update
    sudo apt-get install openjdk-17-jdk -y
    java -version  # Check Java version
  displayName: 'Install OpenJDK 17'

# Build your project with Maven
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'  # Path to your pom.xml file
    goals: 'clean install'  # Build the project
    options: '-DskipTests'  # Skip tests (optional)
  displayName: 'Build with Maven'

# Run unit tests
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'  # Path to your pom.xml file
    goals: 'test'  # Run tests
  displayName: 'Run Unit Tests'

# Publish test results
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'  # Format for test results
    testResultsFiles: '**/target/test-*.xml'  # Path to the test results
    mergeTestResults: true  # Merge test results if there are multiple files
  displayName: 'Publish Test Results'
