services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: cafesystem1
      MYSQL_USER: kouki
      MYSQL_PASSWORD: root_password
    ports:
      - "3306:3306"
    networks:
      - backend

  spring-boot-backend:
    image: demo
    container_name: demo
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/cafesystem1?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: kouki
      SPRING_DATASOURCE_PASSWORD: root_password
    ports:
      - "8087:8086"
    depends_on:
      - mysql
    networks:
      - backend

networks:
  backend:
    driver: bridge
